### ISSUE TITLE
potential alternative to mpl-point-clicker

### ISSUE THREAD

**Issue by ianhi** [Packer-Lab/packerlabimaging#4]
Hi @prajayshah and others

awesome to see that your considering using mpl-point-clicker! If you ever need help with it feel free to ask on discourse.matplotlib.org and I can try to help. 

But what I wanted to mention is: I'm not exactly clear on your use case, but if it's selecting specific data points then you might consider another of my maptlotlib tools: [scatter-selector-widget](https://mpl-interactions.readthedocs.io/en/stable/examples/scatter-selector.html) which is in the mpl-interactions package.

**Comment by prajayshah** [comment]
Hi @ianhi 

Thanks very much for your comments and suggestion! my use case so far was to click retrieve specific datapoint on line plots specifically (see attached screenshots). i adapted mpl-point-clicker for this, it was a little finicky but I managed to get it to work. 

i didn't know about the scatter-selecter-widget, it does look useful as well. would it work for lineplots? or is there another tool you suggest for selecting datapoints on lineplots?

![image](https://user-images.githubusercontent.com/22504586/157529776-7c19fbf8-0e25-4a5b-9f9c-e9a4776c4f36.jpeg)

**Comment by ianhi** [comment]
> i didn't know about the scatter-selecter-widget, it does look useful as well. would it work for lineplots? or is there another tool you suggest for selecting datapoints on lineplots?

currently it does not work for lineplots - although it really should be made to work with them. all that scatter selector is doing is providing a wrapper about the matplotlib `pick` event. All the real work happens here: https://github.com/ianhi/mpl-interactions/blob/8f718e6f000baeccbf71319cbf0d1aab46303963/mpl_interactions/widgets.py#L35-L53

see https://matplotlib.org/stable/gallery/event_handling/pick_event_demo.html for a comprehensive demo of that event

So you can probably just borrow from that to use it with line2d. Though an optimal implementation would also have the option to draw a point over the point closest to the mouse as you moved it around.

If you make any progress towards getting something like that working I'd be happy to accept a PR adding it mpl-interactions :) and also could help you work on the implementation

**Comment by prajayshah** [comment]
good to know! ill follow up with a PR if I end up working on that further at all myself.

closing this issue here for now :)
